[package]
name = "cosmic-logomenu"
version = "0.1.0"
authors = ["PRPLE"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.197"
i18n-embed = { version = "0.14.1", features = [
  "fluent-system",
  "desktop-requester",
] }
i18n-embed-fl = "0.8.0"
rust-embed = "8.3.0"
tokio = "1.36.0"
once_cell = "1.19.0"

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic"
default-features = false
features = ["applet", "tokio", "wayland", "desktop"]

